### PR TITLE
Update Animals Table

### PR DESCRIPTION
**Pull request by MarwanDev**
### In this milestone I:

- Added the species column to the animals table
- Added the transactions required to the queries.sql file and took screenshots below
- Added queries for the questions to the queries.sql file and took screenshots below

screenshot 4
screenshot 1 2
screenshot 1
screenshot 2 2
screenshot 2
screenshot 3 2
screenshot 3
screenshot 4 3
screenshot 4 4
screenshot 4 2

s1
s2
s3
s4

### CODE REVIEW

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
Hi @MarwanDev  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴 

You have submitted a project, that does not have a proper README file

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by MarwanDev** [comment]
Hi @Shedrack-Sunday Thank you for your feedback. Can you please elaborate on what you mean by "proper Readme" as I do not know what kind of change I have to apply? Thank you in advance 😀

**Comment by Shedrack-Sunday** [comment]
Hi, you're already in the Ruby module. By now you're very familiar with how to customize a README file for every project. Please do that appropriately. Thank you

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
Hi @MarwanDev  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴 

You have submitted a project, that does not have a proper README file which is customized from this particular milestone of the project. All fields have to be filled

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by topeogunleye — COMMENTED** [review]
Hi @MarwanDev, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the README file is not complete. Please use the [Microverse template](https://github.com/microverseinc/readme-template).

- [ ] In the case of README consider adapting all the sections for your project. Please replace the template content with content that is meant for your project in this sections:

- Getting Started
- Prerequisites
- Install
- Usage
- Run tests

| professional Readme  | Your Readme that is not professional |
| ------------- | ------------- |
|  Recording 2023-02-14 at 12 52 20 (5)	  | image |

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by DeliceLydia — APPROVED** [review]
## Hi @MarwanDev, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 

## Highlights
- Good job on adding a screenshot in the README
- Git workflow is followed



### Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
